#include <stdio.h>
#include <math.h>
#define PI 3.1415926535

int main(int argc, char *argv[])
{
	int depth = 0;
	int i;
	unsigned char dat;
	double step = 0.f;
	if(argc != 3)
	{
		fprintf(stderr, "Usage %s: <wave-type{sine/triangle/square/bioplar/saw/revsaw}> <wave-depth>  >  out.h\n", argv[0]);
		return -1;
	}

	printf("#ifndef __%s_table_h\n#define __%s_table_h\n/* Automatically generated by wavegenerator, Zhiyuan Wan 2015.7 */\n", argv[1], argv[1]);
	depth = atoi(argv[2]);

	printf("const ");
	if(!strcmp(argv[1], "sine"))
	{
		printf("unsigned char __attribute__ ((section (\".Wavetable\"))) Sine_Table[] = {");
		step = (2 * PI) / depth;
		for(i = 0; i < depth; i++)
		{
			if(i % 8 == 0) putchar('\n');
			dat = sin(step * i) * 127 + 128;
			if(i == (depth - 1)) printf("0x%.2X", dat);
			else printf("0x%.2X,", dat);
		}
		printf("};\n");
	}
	else if(!strcmp(argv[1], "triangle"))
	{
		printf("unsigned char __attribute__ ((section (\".Wavetable\"))) Triangle_Table[] = {");
		step = 128.0f / (depth / 4);
		printf("/* k = %f */", step);
		for(i = 0; i < depth; i++)
		{
			if(i % 8 == 0) putchar('\n');

			if(i < depth / 4) dat = 127 + step * i;
			if(i < 3 * depth / 4 && i >= depth / 4) dat = 255 - step * (i - depth / 4);
			if(i < depth && i >= 3 * depth / 4) dat = step * (i - 3 * depth / 4);

			if(i == (depth - 1)) printf("0x%.2X", dat);
			else printf("0x%.2X,", dat);
		}
		printf("};\n");
	}
	else if(!strcmp(argv[1], "square"))
	{
		printf("unsigned char __attribute__ ((section (\".Wavetable\"))) Square_Table[] = {");
		for(i = 0; i < depth; i++)
		{
			if(i % 8 == 0) putchar('\n');

			if(i < (depth / 2)) dat = 0xff;
			if(i >= (depth / 2)) dat = 0x00;

			if(i == (depth - 1)) printf("0x%.2X", dat);
			else printf("0x%.2X,", dat);
		}
		printf("};\n");
	}
	else if(!strcmp(argv[1], "bioplar"))
	{
		printf("unsigned char __attribute__ ((section (\".Wavetable\"))) Bioplar_Table[] = {");
		for(i = 0; i < depth; i++)
		{
			if(i % 8 == 0) putchar('\n');

			if(i < (depth / 4)) dat = 0x80;
			if(i >= (depth / 4) && i < (depth / 2)) dat = 0xff;
			if(i >= (depth / 2) && i < (3 * depth / 4)) dat = 0x80;
			if(i >= (3 * depth / 4)) dat = 0x00;

			if(i == (depth - 1)) printf("0x%.2X", dat);
			else printf("0x%.2X,", dat);
		}
		printf("};\n");
	}
	else if(!strcmp(argv[1], "saw"))
	{
		printf("unsigned char __attribute__ ((section (\".Wavetable\"))) Sawtooth_Table[] = {");
		step = 255.0f / depth;
		printf("/* k = %f */", step);
		for(i = 0; i < depth; i++)
		{
			if(i % 8 == 0) putchar('\n');

			dat = step * i;
			if(i == (depth - 1)) printf("0x%.2X", dat);
			else printf("0x%.2X,", dat);
		}
		printf("};\n");
	}
	else if(!strcmp(argv[1], "revsaw"))
	{
		printf("unsigned char __attribute__ ((section (\".Wavetable\"))) RevSawtooth_Table[] = {");
		step = 255.0f / depth;
		printf("/* k = %f */", step);
		for(i = 0; i < depth; i++)
		{
			if(i % 8 == 0) putchar('\n');

			dat = 255 - step * i;
			if(i == (depth - 1)) printf("0x%.2X", dat);
			else printf("0x%.2X,", dat);
		}
		printf("};\n");
	}
	else
	{
		fprintf(stderr, "Unknown wave-type as %s!\n", argv[1]);
	}
	printf("#endif\n");
}
